resource.AddFile("materials/icons/fullping.png")
resource.AddFile("materials/icons/3bar.png")
resource.AddFile("materials/icons/2bar.png")
resource.AddFile("materials/icons/1bar.png")
resource.AddFile("materials/icons/kills.png")
resource.AddFile("materials/icons/death.png")
resource.AddFile("materials/icons/group.png")
resource.AddFile("materials/icons/settings.png")
resource.AddFile("materials/icons/kick.png")
resource.AddFile("materials/icons/teleport.png")
resource.AddFile("materials/icons/ban.png")
resource.AddFile("materials/icons/jail.png")
resource.AddFile("materials/icons/return.png")

resource.AddFile("resource/fonts/x14y24pxHeadUpDaisy.ttf")